name: conjur-cloud-apikey

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push events but only for the "main" branch
  # push:
  #   branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher Action
        uses: cyberark/conjur-action@v2.0.5
        with:
          url: ${{ vars.CONJUR_URL }}
          account: ${{ vars.CONJUR_ACCOUNT }}
          host_id: ${{ vars.CONJUR_USERNAME }}
          api_key: ${{ secrets.CONJUR_API_KEY }}
          #secrets: ${{ vars.CONJUR_SECRET_ID_2 }}|SECRET_2
          
      
      - name: 'fetch secrets'
        run: |
          SESSION_TOKEN=$(curl "${{vars.CONJUR_URL}}/authn/${{vars.CONJUR_ACCOUNT}}/${{vars.CONJUR_USERNAME}}/authenticate" -H "Accept-Encoding:base64" -d "${{secrets.CONJUR_API_KEY}}")
          #output=$(curl -H "Authorization: Token token=\"${SESSION_TOKEN}\"" "https://mckesson-prod.secretsmgr.cyberark.cloud/api/secrets/conjur/variable/data/vault/keys-copay-storage-dev/Cloud%20Service-GCPServiceKey-copay-storage-dev-9304-1@gis-iam-prod-3d6b.iam.gserviceaccount.com/password"  | jq )
          echo "masked: vars.CONJUR_URL: ${{ vars.CONJUR_URL }}"
          echo "masked: env.SECRET_2: ${{ env.SECRET_2 }}"
      
      - name: 'capture to file'
        run: |
          echo "capture to file" 
          echo "vars.CONJUR_URL: ${{ vars.CONJUR_URL }}" >> /tmp/env.txt 
          echo "vars.CONJUR_ACCOUNT: ${{ vars.CONJUR_ACCOUNT }}" >> /tmp/env.txt 
          echo "secrets.CONJUR_USERNAME: ${{ secrets.CONJUR_USERNAME }}" >> /tmp/env.txt 
          echo "secrets.CONJUR_API_KEY: ${{ secrets.CONJUR_API_KEY }}" >> /tmp/env.txt 
          echo "env.SECRET_2: ${{ env.SECRET_2 }}" >> /tmp/env.txt 
          echo "" >> /tmp/env.txt 
          echo "env >> /tmp/env.txt" >> /tmp/env.txt 
          env >> /tmp/env.txt 

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: env.txt
          path: /tmp/env.txt
          retention-days: 90
