name: conjur-cloud-apikey

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push events but only for the "main" branch
  # push:
  #   branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher Action
        uses: cyberark/conjur-action@v2.0.5
        with:
          url: ${{ vars.CONJUR_URL }}
          account: ${{ vars.CONJUR_ACCOUNT }}
          host_id: ${{ secrets.CONJUR_USERNAME }}
          api_key: ${{ secrets.CONJUR_API_KEY }}
          secrets: "${{ vars.CONJUR_SECRET_ID_2 }}"|SECRET_2
      
      - name: 'echo set env'
        run: |
          echo "masked: vars.CONJUR_URL: ${{ vars.CONJUR_URL }}"
          echo "masked: env.SECRET_2: ${{ env.SECRET_2 }}"
      
      - name: 'capture to file'
        run: |
          echo "capture to file" 
          echo "vars.CONJUR_URL: ${{ vars.CONJUR_URL }}" >> /tmp/env.txt 
          echo "vars.CONJUR_ACCOUNT: ${{ vars.CONJUR_ACCOUNT }}" >> /tmp/env.txt 
          echo "secrets.CONJUR_USERNAME: ${{ secrets.CONJUR_USERNAME }}" >> /tmp/env.txt 
          echo "secrets.CONJUR_API_KEY: ${{ secrets.CONJUR_API_KEY }}" >> /tmp/env.txt 
          echo "env.SECRET_2: ${{ env.SECRET_2 }}" >> /tmp/env.txt 
          echo "" >> /tmp/env.txt 
          echo "env >> /tmp/env.txt" >> /tmp/env.txt 
          env >> /tmp/env.txt 

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: env.txt
          path: /tmp/env.txt
          retention-days: 90
