name: myworkflow
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push events but only for the "main" branch
  # push:
  #   branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:    
      - name: Import Secrets using CyberArk Conjur Secret Fetcher Action
        uses: cyberark/conjur-action@v2.0.5
        with:
          url: ${{ vars.CONJUR_URL }}
          account: ${{ vars.CONJUR_ACCOUNT }}
          authn_id: ${{ vars.CONJUR_JWT_AUTHN_ID }}
          secrets: ${{ vars.CONJUR_SECRET_ID_1 }}|SECRET_1
      
      - name: 'echo secrets'
        run: |
          echo "masked: env.SECRET_1: ${{ env.SECRET_1 }}"        
          echo "masked: env.SECRET_1: ${{ env.SECRET_1 }}"
      
      - name: 'capture to file'
        run: |
          echo "output file" >> /tmp/output.txt
          echo "vars.CONJUR_URL: ${{ vars.CONJUR_URL }}" >> /tmp/output.txt
          echo "vars.CONJUR_ACCOUNT: ${{ vars.CONJUR_ACCOUNT }}" >> /tmp/output.txt
          echo "vars.CONJUR_JWT_AUTHN_ID: ${{ vars.CONJUR_JWT_AUTHN_ID }}" >> /tmp/output.txt
          echo "vars.CONJUR_SECRET_ID_1: ${{ vars.CONJUR_SECRET_ID_1 }}" >> /tmp/output.txt
          echo "SECRET_1: $SECRET_1" >> /tmp/output.txt
#          echo "" >> /tmp/output.txt
#          echo "env: " >> /tmp/output.txt
#          env >> /tmp/output.txt

      - name: 'upload artifact output.txt'
        uses: actions/upload-artifact@v3
        with:
          name: output.txt
          path: /tmp/output.txt
          retention-days: 90
